#!/usr/bin/env python3

import subprocess
import sys
import re


def log(message):
    print(message, file=sys.stderr)


def stat(program):
    event = "power/energy-pkg/"
    proc = subprocess.run(
        ["perf", "stat", "-e", event, program],
        capture_output=True)
    if proc.returncode != 0:
        raise Exception(f'Return code {proc.returncode}')
    output = proc.stderr.decode('utf-8')

    joules_match = re.search(f'([\\d.,]+) Joules {re.escape(event)}', output)
    joules = float(joules_match.group(1).replace(',', ''))

    seconds_match = re.search('([\\d.,]+) seconds time elapsed', output)
    seconds = float(seconds_match.group(1).replace(',', ''))

    log(f'Program: {program}')
    log(f'  Total energy consumed: {joules} J')
    log(f'  Time: {seconds} s')
    log(f'  Power: {joules / seconds} W')


def main(argv):
    for program in argv:
        stat(program)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
